apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: golist


resources:
- golist-frontend-ingress.yaml
- github.com/christianh814/golist-frontend/deploy

patches:
- patch: |-
    - op: replace
      path: /data/config.json
      value: '{"api": "http://golist-api.7f000001.nip.io/api/products"}'
  target:
    kind: ConfigMap
    name: golist-frontend-config
    version: v1
