apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: golist


resources:
- golist-api-ingress.yaml
- github.com/christianh814/golist-api/deploy

patches:
- patch: |-
    - op: replace
      path: /data/config.json
      value: '{"connection_string":"golist:golist@tcp(database-mariadb:3306)/golist","port":8080}'
  target:
    kind: ConfigMap
    name: golist-api-config
    version: v1
